### PR TITLE
Be able to specify a commit range (default to last tag like before)

### PR DESCRIPTION
**Pull request by hzoo**
Implementation might suck, but you get the idea?

Can also add docs

``` bash
# default
./node_modules/.bin/lerna-changelog
# auto add .. to range
./node_modules/.bin/lerna-changelog v6.11.6..
./node_modules/.bin/lerna-changelog v6.11.5..v6.11.6
```

### CODE REVIEW

**Comment by hzoo** [comment]
Oh this is https://github.com/lerna/lerna-changelog/issues/17 almost

**Comment by gigabo** [comment]
Each commit should get its own changelog entry, right?

So `lerna-changelog v6.11.0..v6.11.6` should make _six_ separate entries?

**Comment by hzoo** [comment]
Oh I see.. didn't even think about that.. maybe then it makes more sense to just specify the 1 version and it just gets the next tag so v6.11.0 would = v6.11.0..v6.11.1 and make that changelog

I dono whatever seems more intuitive

**Comment by gigabo** [comment]
> v6.11.0 would = v6.11.0..v6.11.1

I think I would expect `lerna-changelog v6.11.0` to make a changelog entry _for_ v6.11.0 rather than _starting at_ v6.11.0 (which is actually the changes _in_ v6.11.1).

**Comment by hzoo** [comment]
Right that makes sense

**Comment by hzoo** [comment]
I think we should just do that unless it's really easy to make the multi changelog too (not a usecase for me yet so could be another issue/pr for someone)

**Pull request closed without merging**
