### PR TITLE
chore(dep): update yargs to ^14.0.0

### PR DESCRIPTION
**Pull request by trivikr**

### CODE REVIEW

**Comment by trivikr** [comment]
rebased from master

**Comment by Turbo87** [comment]
did you check if the breaking changes between those versions affect us?

**Comment by trivikr** [comment]
breaking changes are documented here https://github.com/yargs/yargs/blob/master/CHANGELOG.md

## 14.0.0

* we now only officially support yargs.$0 parameter and discourage direct access to yargs.parsed
* previously to this fix methods like `yargs.getOptions()` contained the state of the last command to execute.
* do not allow additional positionals in strict mode

## 13.0.0

* options with leading '+' or '0' now parse as strings
* see [yargs-parser@12.0.0 CHANGELOG](https://github.com/yargs/yargs-parser/blob/master/CHANGELOG.md#breaking-changes)
* we now warn if the yargs stanza package.json is used.

## 12.0.0

* Options absent from `argv` (not set via CLI argument) are now absent from the parsed result object rather than being set with `undefined`
* drop Node 4 from testing matrix, such that we'll gradually start drifting away from supporting Node 4.
* yargs-parser does not populate 'false' when boolean flag is not passed
* tests that assert against help output will need to be updated

The CI was successful, but I'm closing this PR as we're planning to use dependabot and follow up Node.js release schedule in #148

**Comment by Turbo87** [comment]
tbh I'm not sure if CI is testing that part of the application 😅

**Pull request closed without merging**
