### PR TITLE
chore: add dependabot badge in README

### PR DESCRIPTION
**Pull request by trivikr**
This will show dependabot status in README
dependabot-status

It's inactive right now https://api.dependabot.com/badges/status?host=github&repo=lerna/lerna-changelog
Can be viewed at https://github.com/trivikr/lerna-changelog/tree/patch-1

### CODE REVIEW

**Comment by Turbo87** [comment]
what value does this bring us?

**Comment by trivikr** [comment]
Value: the dependencies in this repo are automatically updated by dependabot

**Comment by Turbo87** [comment]
yeah, but they are updated already without having the badge 🤔

**Comment by trivikr** [comment]
> yeah, but they are updated already without having the badge 🤔

That's known by @Turbo87 and other contributors/collaborators.

Having this badge in README will give confidence to new users who just land on GitHub repo.

**Comment by Turbo87** [comment]
IMHO this clutters the README for no good reason, so I'll prefer to not merge this. sorry.

**Pull request closed without merging**
