### PR TITLE
add support for Github Enterprise

### PR DESCRIPTION
**Pull request by longlho**
@hzoo @gigabo via `enterpriseUrl` config value & `GITHUB_ENTERPRISE_AUTH` token

### CODE REVIEW

**Comment by longlho** [comment]
@reid @redonkulus in case u guys are interested

**Comment by Turbo87** [comment]
@longlho this might introduce problems with the current implementation of the API cache since the data from the public GitHub server and the data from the private server are getting mixed up

**Comment by pselden** [comment]
This would be nice to have.

**Comment by JabbyPanda** [comment]
That would indeed would be beneficial

One more thing has to be changed in [configuration.ts](https://github.com/lerna/lerna-changelog/blob/master/src/configuration.ts#L123) file

`findRepoFromPkg` method shall take value of enterprise URL param into the account as well

**Comment by longlho** [comment]
closing this PR since it's super old and I haven't got time to work on it :)

**Pull request closed without merging**
