### PR TITLE
chore(dep): upgrade make-fetch-happen to ^5.0.0

### PR DESCRIPTION
**Pull request by trivikr**

### CODE REVIEW

**Comment by Turbo87** [comment]
I can't find any references to a v5 release at https://github.com/zkat/make-fetch-happen. Do you know what changed between those releases and why it is not part of the repo?

**Comment by trivikr** [comment]
I've created an issue with the repo at https://github.com/zkat/make-fetch-happen/issues/69

**Comment by isaacs** [comment]
https://github.com/npm/make-fetch-happen/blob/latest/CHANGELOG.md

**Comment by Turbo87** [comment]
thanks @isaacs! looks like the breaking change doesn't affect us.

@trivikr we currently have a merge conflict in the `yarn.lock` file. can you rebase this PR? I guess we might as well migrate to v6.0.0, which was just released two days ago.

**Comment by trivikr** [comment]
> can you rebase this PR? I guess we might as well migrate to v6.0.0, which was just released two days ago.

PR rebased, and upgraded to make-fetch-happen@^6.0.0

**Comment by Turbo87** [comment]
argh, sorry, their changelog does not mention that Node.js 8 is now required in v6.0.0

**Comment by trivikr** [comment]
@Turbo87 Can we release lerna-changelog 1.0.0 deprecating Node.js 6.x as suggested in https://github.com/lerna/lerna-changelog/pull/147#issuecomment-536319541?

The last 0.x release was in Oct 2018, and a major version bump is due! https://github.com/lerna/lerna-changelog/releases

**Comment by Turbo87** [comment]
I'm a bit hesitant because Node 8 will be EOL at the end of the year, so we might as well wait until then and then drop Node 8 support as well. 🤔

**Comment by trivikr** [comment]
> I'm a bit hesitant because Node 8 will be EOL at the end of the year, so we might as well wait until then and then drop Node 8 support as well. 🤔

Why not drop Node 8 support in v2.0.0?
This way your clients will have an option to choose whichever version of `lerna-changelog` they want, based on Node.js version.

**Comment by trivikr** [comment]
forced update to `make-fetch-happen@^5.0.0` version as of now

**Pull request merged**
